# Project Name
TARGET = simple-arpeggiator-touch

# Sources
CPP_SOURCES = simple-arpeggiator-touch.cpp

# Library Locations
LIBDAISY_DIR = ../lib/libDaisy/
DAISYSP_DIR = ../lib/DaisySP/

# Core location, and generic Makefile.
SYSTEM_FILES_DIR = $(LIBDAISY_DIR)/core
include $(SYSTEM_FILES_DIR)/Makefile
