# Project Name
TARGET = simple-looper-touch

# Sources
CPP_SOURCES = simple-looper-touch.cpp

# Library Locations
LIBDAISY_DIR = ../lib/libDaisy/
DAISYSP_DIR = ../lib/DaisySP/

# Core location, and generic Makefile.
SYSTEM_FILES_DIR = $(LIBDAISY_DIR)/core
include $(SYSTEM_FILES_DIR)/Makefile

# Support constexpr array
CPP_STANDARD = -std=gnu++17
